name: t_flutter
description: A new Flutter module project.
publish_to: none
version: 0.0.8

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  talkjs_flutter: 0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.t_flutter
    iosBundleIdentifier: com.example.tFlutter
